---
apiVersion: v1
kind: Namespace
metadata:
  name: conformance
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: conformance
  namespace: conformance
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: conformance
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: conformance
  namespace: conformance
---
apiVersion: v1
kind: Pod
metadata:
  name: e2e-producer-consumer-test
  namespace: conformance
spec:
  serviceAccountName: conformance
  containers:
  - name: conformance-container
    image: gcr.io/heptio-images/kube-conformance:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: E2E_FOCUS
      value: "Conformance"
    - name: E2E_SKIP
      value: "Alpha|Disruptive|Feature|Flaky|Kubectl"
    - name: E2E_PROVIDER
      value: local
    volumeMounts:
    - name: output-volume
      mountPath: /tmp/results
  volumes:
  - name: output-volume
    hostPath:
      path: /tmp/results
  restartPolicy: Never
