apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Chart.Name }}
data:
  mpd.conf: |
    user "mpd"
    bind_to_address "127.0.0.1"
    port "6600"
    music_directory "/mpd/music"
    playlist_directory "/mpd/cache/playlists"
    db_file "/mpd/cache/tag_cache"
    state_file "/mpd/cache/state"
    sticker_file "/mpd/cache/sticker.sql"
    filesystem_charset "UTF-8"
    resampler {
      plugin "soxr"
      threads "0"
      quality "very high"
    }
    audio_output {
      type "httpd"
      name "HTTP FLAC-3"
      tags "yes"
      format "48000:24:2"
      always_on "yes"
      encoder "flac"
      compression "3"
      port "8000"
      bind_to_address "0.0.0.0"
      max_clients "0"
    }