apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Chart.Name }}
data:
  mpd.conf: |
    bind_to_address "127.0.0.1"
    port "{{ .Values.mpd.controlPort }}"
    music_directory "http://127.0.0.1:{{ .Values.rclone.webDavPort }}/"
    playlist_directory "{{ .Values.mpd.cachePath }}/playlists"
    db_file "{{ .Values.mpd.cachePath }}/tag_cache"
    state_file "{{ .Values.mpd.cachePath }}/state"
    sticker_file "{{ .Values.mpd.cachePath }}/sticker.sql"
    filesystem_charset "UTF-8"
{{- range $audioOutput := .Values.audioOutputs }}
    audio_output {
      type "httpd"
      name "{{ $audioOutput.name }}"
      port "{{ $audioOutput.port }}"
      bind_to_address "0.0.0.0"
{{- range $k, $v := $audioOutput.config }}
      {{ $k }} "{{ $v }}"
{{- end }}
    }
{{- end }}