apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mpd-cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.storageClass }}
  volumeMode: Filesystem