kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
  - name: ympd-ui
    port: {{ .Values.ympd.uiPort }}
{{- range $audioOutput := .Values.audioOutputs }}
  - name: {{ $audioOutput.name }}
    port: {{ $audioOutput.port }}
{{- end }}
  selector:
    app: {{ .Chart.Name }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  annotations:
    # kubernetes.io/ingress.class: "{{ .Values.ingressClass }}"
    cert-manager.io/issuer: "{{ .Values.certIssuer }}"
spec:
  ingressClassName: {{ .Values.ingressClass }}
  tls:
  - hosts:
    - {{ .Values.ingress }}
    secretName: {{ .Values.certSecretName }}
  rules:
  - host: {{ .Values.ingress }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: {{ .Values.ympd.uiPort }}
{{- range $audioOutput := .Values.audioOutputs }}
      - path: /{{ $audioOutput.name }}
        pathType: Prefix
        backend:
          service:
            name: {{ $.Chart.Name }}
            port:
              number: {{ $audioOutput.port }}
{{- end }}
