apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mpd.fullname" . }}
  labels:
    app: {{ template "mpd.name" . }}
    chart: {{ template "mpd.chart" . }}
    release: {{ .Release.Name }}
stringData:
  mpd.conf: |
    bind_to_address    "{{ .Values.paths.mpdSocket }}/socket"
    music_directory    "http://127.0.0.1:{{ .Values.ports.rclone }}/"
    sticker_file       "{{ .Values.paths.mpdCache }}/sticker.sql"
    playlist_directory "{{ .Values.paths.mpdCache }}/playlists"
    state_file         "{{ .Values.paths.mpdCache }}/state"
    database {
      plugin          "simple"
      path            "{{ .Values.paths.mpdCache }}/tag_cache"
      cache_directory "{{ .Values.paths.mpdCache }}/cache"
    }
{{- range $k, $v := .Values.config }}
    {{ $k }} "{{ $v }}"
{{- end }}
{{- range $audioOutput := .Values.audioOutputs }}
    audio_output {
      type "httpd"
      name "{{ $audioOutput.name }}"
      port "{{ $audioOutput.port }}"
      bind_to_address "0.0.0.0"
{{- range $k, $v := $audioOutput.config }}
      {{ $k }} "{{ $v }}"
{{- end }}
    }
{{- end }}