{{- if .Values.audioOutputs -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mpd.fullname" . }}
  labels:
    app: {{ template "mpd.name" . }}
    chart: {{ template "mpd.chart" . }}
    release: {{ .Release.Name }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end }}
  ports:
{{- range $audioOutput := .Values.audioOutputs }}
  - name: {{ $audioOutput.name }}
    port: {{ $audioOutput.port }}
    protocol: TCP
{{- if (and (eq $.Values.service.type "NodePort") ( $audioOutput.nodePort)) }}
    nodePort: {{ $audioOutput.nodePort }}
{{- else }}
    targetPort: {{ $audioOutput.port }}
{{- end }}
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{- range $i , $ip := .Values.service.externalIPs }}
  - {{ $ip }}
{{- end }}
{{- end }}
  selector:
    app: {{ template "mpd.name" . }}
    release: {{ .Release.Name }}
{{- end }}