variant: fcos
version: ${ignition_version}
storage:
  files:
    - path: /etc/systemd/network/20-${apiserver_interface_name}.network.d/20-kubernetes-master-static-routes.conf
      mode: 0644
      contents:
        inline: |
          [RoutingPolicyRule]
          Priority=${route_table_priority}
          Table=${route_table_id}
          From=${apiserver_ip}/32
          To=${route_destination_prefix}