apiVersion: v1
kind: ConfigMap
metadata:
  name: mpd-config
  namespace: common
data:
  mpd.conf: |
    user "mpd"
    bind_to_address "127.0.0.1"
    port "6600"
    music_directory "/mpd/music"
    playlist_directory "/mpd/cache/playlists"
    db_file "/mpd/cache/tag_cache"
    state_file "/mpd/cache/state"
    sticker_file "/mpd/cache/sticker.sql"
    filesystem_charset "UTF-8"
    resampler {
      plugin "soxr"
      threads "0"
      quality "very high"
    }
    audio_output {
      type "httpd"
      name "HTTP FLAC-3"
      tags "yes"
      format "48000:32:2"
      always_on "yes"
      encoder "flac"
      compression "3"
      port "8000"
      bind_to_address "0.0.0.0"
      max_clients "0"
    }
    audio_output {
      type "httpd"
      name "HTTP lossy"
      encoder "vorbis"
      port "8001"
      tags "yes"
      format "44100:16:2"
      always_on "yes"
    }
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mpd
  namespace: common
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpd
  template:
    metadata:
      labels:
        app: mpd
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      containers:
      - name: mpd
        imagePullPolicy: Always
        image: randomcoww/mpd:0.22.1
        ports:
        - containerPort: 8000
          protocol: TCP
        - containerPort: 8001
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/mpd.conf
          name: mpd-config
          subPath: mpd.conf
        - mountPath: /mpd/music
          name: mpd-data
        - mountPath: /mpd/cache
          name: mpd-cache
      - name: ympd
        imagePullPolicy: Always
        image: randomcoww/ympd:latest
        args:
        - "-h"
        - "127.0.0.1"
        - "-p"
        - "6600"
        - "-w"
        - "8080"
        ports:
        - containerPort: 8080
          protocol: TCP
      volumes:
      - name: mpd-cache
        hostPath:
          path: /var/lib/kubelet/pv/tmp/mpd-cache
          type: DirectoryOrCreate
      - name: mpd-config
        configMap:
          name: mpd-config
      - name: mpd-data
        persistentVolumeClaim:
          claimName: mpd-data-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: mpd
  namespace: common
spec:
  ports:
  - name: flac
    port: 8000
  - name: lossy
    port: 8001
  - name: control
    port: 8080
  selector:
    app: mpd
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mpd
  namespace: common
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: mpd.fuzzybunny.internal
    http:
      paths:
      - path: /
        backend:
          serviceName: mpd
          servicePort: control
  - host: s.fuzzybunny.internal
    http:
      paths:
      - path: /flac
        backend:
          serviceName: mpd
          servicePort: flac
      - path: /lossy
        backend:
          serviceName: mpd
          servicePort: lossy
  tls:
  - secretName: tls-ingress

# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: mpd-ext
#   namespace: common
# spec:
#   type: LoadBalancer
#   loadBalancerIP: 192.168.94.125
#   ports:
#   - name: lossy
#     port: 8080
#     targetPort: 8001
#   selector:
#     app: mpd