{
 "title": "Kea-dhcp4",
 "description": "Prometheus Kea exporter metrics.",
 "tags": [
  "Prometheus",
  "Kea-dhcp"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values({__name__=~\"kea_dhcp.*\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ACK",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kea_dhcp4_packets_sent_total{instance=~\"$host\", operation=\"ack\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv4)"
    },
    {
     "expr": "sum(kea_dhcp6_packets_sent_total{instance=~\"$host\", operation=\"ack\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv6)"
    },
    {}
   ]
  },
  {
   "title": "Offer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kea_dhcp4_packets_sent_total{instance=~\"$host\", operation=\"offer\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv4)"
    },
    {
     "expr": "sum(kea_dhcp6_packets_sent_total{instance=~\"$host\", operation=\"offer\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv6)"
    }
   ]
  },
  {
   "title": "Request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kea_dhcp4_packets_received_total{instance=~\"$host\", operation=\"request\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv4)"
    },
    {
     "expr": "sum(kea_dhcp6_packets_received_total{instance=~\"$host\", operation=\"request\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv6)"
    }
   ]
  },
  {
   "title": "Discover",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kea_dhcp4_packets_received_total{instance=~\"$host\", operation=\"discover\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv4)"
    },
    {
     "expr": "sum(kea_dhcp6_packets_received_total{instance=~\"$host\", operation=\"discover\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv6)"
    }
   ]
  },
  {
   "title": "Addresses declined",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kea_dhcp4_addresses_declined_total{instance=~\"$host\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv4)"
    }
   ]
  },
  {
   "title": "Addresses declined reclaimed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kea_dhcp4_addresses_declined_reclaimed_total{instance=~\"$host\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv4)"
    }
   ]
  },
  {
   "title": "Addresses reclaimed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kea_dhcp4_addresses_reclaimed_total{instance=~\"$host\"}) by (instance)",
     "legendFormat": "{{instance}} (ipv4)"
    }
   ]
  }
 ]
}