---
variant: fcos
version: 1.4.0
systemd:
  units:
    # systemd-networkd work around "could not connect to dbus: permission denied"
    - name: systemd-networkd.service
      enabled: true
      dropins:
        - name: 10-dependencies.conf
          contents: |
            [Unit]
            After=dbus.socket
    - name: systemd-network-generator.service
      mask: true
    - name: systemd-networkd-wait-online.service
      enabled: true
    - name: NetworkManager.service
      mask: true
    - name: NetworkManager-wait-online.service
      mask: true

storage:
  files:
    - path: /etc/sysctl.d/99-wlan-bridge.conf
      mode: 0644
      contents:
        inline: |
          net.bridge.bridge-nf-call-iptables=0
    # systemd-networkd defaults
    # CNI may fail if systemd-networkd tries to manage it
    - path: /etc/systemd/network/91-default.network
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=*

          [Link]
          Unmanaged=true

          [Network]
          LinkLocalAddressing=false
          DHCP=false
