{{- $fullName := "kapprover" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    chart: {{ template "cluster-services.chart" . }}
    release: "{{ .Release.Name }}"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    chart: {{ template "cluster-services.chart" . }}
    release: "{{ .Release.Name }}"
rules:
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests"]
  verbs: ["get", "list", "delete", "watch"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests/approval"]
  verbs: ["update"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["signers"]
  resourceNames: ["kubernetes.io/kubelet-serving"]
  verbs: ["approve"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    chart: {{ template "cluster-services.chart" . }}
    release: "{{ .Release.Name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $fullName }}
subjects:
- kind: ServiceAccount
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    chart: {{ template "cluster-services.chart" . }}
    release: "{{ .Release.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $fullName }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $fullName }}
        release: {{ .Release.Name }}
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: {{ $fullName }}
      containers:
      - name: {{ $fullName }}
        image: {{ .Values.images.kapprover }}
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 50Mi