{{- $fullName := "kube-proxy" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    chart: {{ template "cluster-services.chart" . }}
    release: "{{ .Release.Name }}"
data:
  kube-proxy-config.yaml: |
    kind: KubeProxyConfiguration
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    mode: ipvs
    clusterCIDR: {{ .Values.podNetworkPrefix }}
    healthzBindAddress: 127.0.0.1:{{ .Values.ports.kubeProxy }}
    ipvs:
      strictARP: true