apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: mayastor
spec:
  privileged: true
  hostNetwork: true
  volumes: ['*']
  hostPorts:
  - min: 0
    max: 65535
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mayastor-psp
rules:
- apiGroups: ["extensions"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
  resourceNames: ["mayastor"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mayastor-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mayastor-psp
subjects:
- kind: ServiceAccount
  name: default
  namespace: mayastor
- kind: ServiceAccount
  name: moac
  namespace: mayastor