kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mayastor-nvmf
parameters:
  repl: '2'
  protocol: 'nvmf'
provisioner: io.openebs.csi-mayastor
reclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms-volume-claim
  namespace: common
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4084Mi
  storageClassName: mayastor-nvmf

---
apiVersion: v1
kind: Pod
metadata:
  name: basic-pod
  namespace: common
spec:
  containers:
  - image: alpine:edge
    command:
    - "tail"
    - "-f"
    - "/dev/null"
    imagePullPolicy: Always
    name: basic-pod
    volumeMounts:
    - mountPath: "/volume"
      name: ms-volume
  restartPolicy: Always
  dnsPolicy: ClusterFirstWithHostNet
  volumes:
  - name: ms-volume
    persistentVolumeClaim:
      claimName: ms-volume-claim