{{- if .Values.ingress.enabled -}}
{{- $fullName := include "dev.fullname" . -}}
{{- $servicePort := .Values.ports.dev -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: {{ template "dev.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "dev.name" . }}
    chart: {{ template "dev.chart" . }}
    release: {{ .Release.Name }}
{{- with .Values.ingress.labels }}
{{ toYaml . | indent 4 }}
{{- end }}

{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - http:
        paths:
          - path: {{ $ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
      {{- if . }}
      host: {{ . | quote }}
      {{- end }}
  {{- end }}
{{- end }}