apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    k8s-app: external-dns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    k8s-app: external-dns
rules:
- apiGroups: [""]
  resources: ["endpoints", "pods", "services", "nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    k8s-app: external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: {{ .Release.Namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    k8s-app: external-dns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: external-dns
  template:
    metadata:
      labels:
        k8s-app: external-dns
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/external-dns-configmap.yaml") . | sha256sum }}
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: external-dns
      containers:
      - name: coredns
        image: {{ .Values.images.coredns }}
        imagePullPolicy: Always
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
        ports:
        - containerPort: 53
          protocol: UDP
        - containerPort: 53
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      - name: etcd
        image: {{ .Values.images.etcd }}
        command: [ "/usr/local/bin/etcd" ]
      - name: external-dns
        image: {{ .Values.images.external_dns }}
        args:
        - --source=service
        - --source=ingress
        - --provider=coredns
        - --log-level=debug
        - --domain-filter={{ .Values.cluster_domain }}
      dnsPolicy: Default
      volumes:
      - name: config-volume
        configMap:
          name: external-dns
          items:
          - key: Corefile
            path: Corefile

---
kind: Service
apiVersion: v1
metadata:
  name: external-dns-tcp
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    k8s-app: external-dns
  annotations:
    metallb.universe.tf/allow-shared-ip: external-dns
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.external_dns_ip }}
  ports:
  - name: default
    port: 53
    protocol: TCP
  selector:
    k8s-app: external-dns

---
kind: Service
apiVersion: v1
metadata:
  name: external-dns-udp
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    k8s-app: external-dns
  annotations:
    metallb.universe.tf/allow-shared-ip: external-dns
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.external_dns_ip }}
  ports:
  - name: default
    port: 53
    protocol: UDP
  selector:
    k8s-app: external-dns