{{- $fullName := "flannel" -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    chart: {{ template "cluster-services.chart" . }}
    release: "{{ .Release.Name }}"
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "cniVersion": "{{ .Values.cniVersion }}",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "type": "bridge",
            "hairpinMode": true,
            "isDefaultGateway": true,
            "bridge": "{{ .Values.cniInterfaceName }}"
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "{{ .Values.podNetworkPrefix }}",
      "Backend": {
        "Type": "host-gw"
      }
    }