{{- $fullName := "kube-proxy" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    chart: {{ template "cluster-services.chart" . }}
    release: "{{ .Release.Name }}"

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-proxy
  labels:
    app: {{ $fullName }}
    release: "{{ .Release.Name }}"
roleRef:
  kind: ClusterRole
  name: system:node-proxier
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    release: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      app: {{ $fullName }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $fullName }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/kube-proxy-configmap.yaml") . | sha256sum }}
    spec:
      priorityClassName: system-node-critical
      hostNetwork: true
      serviceAccountName: {{ $fullName }}
      tolerations:
      - operator: Exists
        effect: NoExecute
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: {{ $fullName }}
        image: {{ .Values.images.kubeProxy }}
        command:
        - kube-proxy
        - --config=/etc/kube-proxy/kube-proxy-config.yaml
        - --v=2
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: "{{ .Values.apiServerIP }}"
        - name: KUBERNETES_SERVICE_PORT
          value: "{{ .Values.ports.apiServer }}"
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /run/xtables.lock
          name: xtables-lock
        - name: kube-proxy-config
          mountPath: /etc/kube-proxy/
        livenessProbe:
          httpGet:
            scheme: HTTP
            host: 127.0.0.1
            port: {{ .Values.ports.kubeProxy }}
            path: /healthz
          initialDelaySeconds: 15
          timeoutSeconds: 15
      volumes:
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
      - name: kube-proxy-config
        configMap:
          name: {{ $fullName }}