apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    k8s-app: kube-dns
data:
  Corefile: |
    . {
      errors
      health
      kubernetes {{ .Values.cluster_domain }} in-addr.arpa ip6.arp {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
      }
      forward . {{ .Values.forwarding_dns_ip }}
      cache 30
      reload
      loadbalance
    }