apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "desktop.fullname" . }}
  labels:
    app: {{ template "desktop.name" . }}
    chart: {{ template "desktop.chart" . }}
    release: "{{ .Release.Name }}"
spec:
  serviceName: {{ template "desktop.fullname" . }}
  # Only supports 1 replica
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "desktop.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "desktop.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      restartPolicy: Always
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.images.desktop }}
        env:
        - name: USER
          value: {{ .Values.user }}
        - name: HOME
          value: /home/{{ .Values.user }}
        - name: UID
          value: {{ .Values.uid | quote }}
        - name: XDG_RUNTIME_DIR
          value: /run/user/{{ .Values.uid }}
        - name: DISPLAY
          value: {{ .Values.kasm.display }}
        {{- range $k, $v := .Values.kasm.additionalEnvs }}
        - name: {{ $k }}
          value: {{ join "," $v | quote }}
        {{- end }}
        volumeMounts:
        - name: desktop-home
          mountPath: /home/{{ .Values.user }}
        - name: dshm
          mountPath: /dev/shm
        - name: secret
          mountPath: /etc/ssh/ssh_known_hosts
          subPathExpr: ssh_known_hosts
          readOnly: true
        ports:
        - containerPort: {{ .Values.ports.kasm }}
        {{- range $port := .Values.ports.sunshineTCP }}
        - containerPort: {{ $port }}
        {{- end }}
        {{- range $port := .Values.ports.sunshineUDP }}
        - containerPort: {{ $port }}
          protocol: "UDP"
        {{- end }}
        securityContext:
          capabilities:
            add:
            - AUDIT_WRITE
      {{- with .Values.kasm.resources }}
        resources:
{{ toYaml . | indent 10 }}
      {{- end }}
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: secret
        secret:
          secretName: {{ template "desktop.fullname" . }}
  volumeClaimTemplates:
  - metadata:
      name: desktop-home
    {{- if .Values.persistence.annotations }}
      annotations:
{{ toYaml .Values.persistence.annotations | trimSuffix "\n" | indent 8 }}
    {{- end }}
    spec:
      accessModes:
      - {{ .Values.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
    {{- if .Values.persistence.storageClass }}
      storageClassName: "{{ .Values.persistence.storageClass }}"
    {{- end }}