---
variant: fcos
version: ${ignition_version}
systemd:
  units:
    - name: chronyd.service
      enabled: true
    # enable trim on all disks
    - name: fstrim.service
      enabled: true
      dropins:
        - name: 10-all.conf
          contents: |
            [Service]
            ExecStart=
            ExecStart=/usr/sbin/fstrim --all --verbose --quiet
    - name: systemd-network-generator.service
      mask: true
    - name: systemd-resolved.service
      enabled: true
    # temperature monitoring for hardware
    - name: lm_sensors.service
      enabled: true
      dropins:
        - name: 10-exclude-vm.conf
          contents: |
            [Unit]
            ConditionVirtualization=!vm
            ConditionVirtualization=!container
    # configure nftables service as template
    - name: nftables.service
      mask: false
    - name: nftables@.service
      enabled: true
      contents: |
        [Unit]
        Wants=network-pre.target
        Before=network-pre.target
        ConditionFileNotEmpty=/etc/nftables/%i.nft

        [Service]
        Type=oneshot
        ProtectSystem=full
        ProtectHome=true
        ExecStart=/sbin/nft -f /etc/nftables/%i.nft
        ExecReload=/sbin/nft 'delete table %i; include "/etc/nftables/%i.nft";'
        ExecStop=/sbin/nft delete table %i
        RemainAfterExit=yes

        [Install]
        WantedBy=multi-user.target

storage:
  files:
    - path: /etc/hostname
      mode: 0644
      contents:
        inline:
          ${hostname}

    - path: /etc/systemd/resolved.conf.d/10-base.conf
      mode: 0644
      contents:
        inline: |
          [Resolve]
          DNSStubListener=false
          MulticastDNS=true
          LLMNR=false
    # Block password SSH #
    - path: /etc/ssh/sshd_config.d/10-block-password.conf
      mode: 0644
      contents:
        inline: |
          PasswordAuthentication no
    # Systemd for live image #
    - path: /etc/systemd/journald.conf.d/10-live-boot-config.conf
      mode: 0644
      contents:
        inline: |
          [Journal]
          Storage=volatile
          RuntimeMaxUse=10M
          SystemMaxUse=10M
          SystemMaxFileSize=10M
          ForwardToSyslog=false
          ForwardToConsole=false
    - path: /etc/systemd/system.conf.d/10-live-boot-config.conf
      mode: 0644
      contents:
        inline: |
          [Manager]
          DumpCore=false
    # Disable speaker #
    - path: /etc/modprobe.d/10-blacklist-pcspk.conf
      mode: 0644
      contents:
        inline: |
          blacklist pcspkr
          blacklist snd_pcsp
    # DNS reply from unexpected source #
    - path: /etc/modules-load.d/20-dns-reply.conf
      mode: 0644
      contents:
        inline: |
          br_netfilter
    # Image build #
    - path: /etc/modules-load.d/20-uinput.conf
      mode: 0644
      contents:
        inline: |
          uinput
    # common #
    - path: /etc/sysctl.d/10-common.conf
      mode: 0644
      contents:
        inline: |
          kernel.printk=4
          fs.inotify.max_user_watches=524288
    # needed if bridging wlan
    - path: /etc/sysctl.d/99-bridge-iptables.conf
      mode: 0644
      contents:
        inline: |
          net.bridge.bridge-nf-call-iptables=0