apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vaultwarden.fullname" . }}
  labels:
    app: {{ template "vaultwarden.name" . }}
    chart: {{ template "vaultwarden.chart" . }}
    release: {{ .Release.Name }}
stringData:
  ACCESS_KEY_ID: "{{ .Values.backup.accessKeyID }}"
  SECRET_ACCESS_KEY: "{{ .Values.backup.secretAccessKey }}"