apiVersion: v1
kind: Pod
metadata:
  name: basic-pod
  namespace: default
spec:
  containers:
  - image: alpine:edge
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: basic-pod
  restartPolicy: Always
  dnsPolicy: ClusterFirstWithHostNet