{
 "title": "gateway-0",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "kubelet",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"gateway-0\",unit=\"kubelet.service\"}"
    }
   ]
  },
  {
   "title": "keepalived",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{host=\"gateway-0\",container_name=\"keepalived\"}"
    }
   ]
  },
  {
   "title": "kea-dhcp4",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{host=\"gateway-0\",container_name=\"kea-dhcp4\"}"
    }
   ]
  }
 ]
}
{
 "title": "gateway-1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "kubelet",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"gateway-1\",unit=\"kubelet.service\"}"
    }
   ]
  },
  {
   "title": "keepalived",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{host=\"gateway-1\",container_name=\"keepalived\"}"
    }
   ]
  },
  {
   "title": "kea-dhcp4",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{host=\"gateway-1\",container_name=\"kea-dhcp4\"}"
    }
   ]
  }
 ]
}
{
 "title": "controller-0",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "kubelet",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"controller-0\",unit=\"kubelet.service\"}"
    }
   ]
  },
  {
   "title": "etcd",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{host=\"controller-0\",container_name=\"etcd\"}"
    }
   ]
  },
  {
   "title": "kube-apiserver",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{host=\"controller-0\",container_name=\"kube-apiserver\"}"
    }
   ]
  }
 ]
}
{
 "title": "controller-1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "kubelet",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"controller-1\",unit=\"kubelet.service\"}"
    }
   ]
  },
  {
   "title": "etcd",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{host=\"controller-1\",container_name=\"etcd\"}"
    }
   ]
  },
  {
   "title": "kube-apiserver",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{host=\"controller-1\",container_name=\"kube-apiserver\"}"
    }
   ]
  }
 ]
}
{
 "title": "controller-2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "kubelet",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"controller-2\",unit=\"kubelet.service\"}"
    }
   ]
  },
  {
   "title": "etcd",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{host=\"controller-2\",container_name=\"etcd\"}"
    }
   ]
  },
  {
   "title": "kube-apiserver",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{host=\"controller-2\",container_name=\"kube-apiserver\"}"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API server request rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Worker load (15m)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load15", "legendFormat": "{{kubernetes_node}}" }
   ]
  },
  {
   "title": "API server request latency p90",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_latencies_bucket{verb != \"WATCH\"}[5m])) by (le, verb)) / 1e3",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Worker memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Etcd request duration p90",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\rhistogram_quantile(0.90, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Worker disk I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total[2m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}