kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: music-rclone-vol
spec:
  selector:
    matchLabels:
      app: music-rclone-vol
  template:
    metadata:
      labels:
        app: music-rclone-vol
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      # Mount fuse in mnt under base path so that client container
      # can verify that it is mounted before starting
      volumes:
      - name: music-rclone-vol
        hostPath:
          path: /hostpath/music/mnt
          type: DirectoryOrCreate
      containers:
      - name: rclone
        imagePullPolicy: Always
        image: randomcoww/rclone:v1.50.1
        securityContext:
          privileged: true
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-auth
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-auth
              key: secret_access_key
        args:
        - "mount"
        - ":s3:music/"
        - "/vol"
        - "--s3-provider=Minio"
        - "--s3-env-auth=true"
        - "--s3-region="
        - "--s3-endpoint=http://minio.default.svc.cluster.local:9000"
        - "--allow-other"
        - "--vfs-cache-mode=minimal"
        - "--no-modtime"
        - "--read-only"
        volumeMounts:
        - name: music-rclone-vol
          mountPath: /vol
          mountPropagation: Bidirectional

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-pv
spec:
  storageClassName: music
  capacity:
    storage: 10Ti
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /hostpath/music
    type: Directory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-pvc
spec:
  accessModes:
  - ReadOnlyMany
  storageClassName: music
  resources:
    requests:
      storage: 10Ti