apiVersion: openebs.io/v1alpha1
kind: StoragePool
metadata:
  name: transmission
  type: hostdir
spec:
  path: "/pv/transmission"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-transmission
  annotations:
    openebs.io/cas-type: jiva
    cas.openebs.io/config: |
      - name: ReplicaCount
        value: "2"
      - name: StoragePool
        value: transmission
provisioner: openebs.io/provisioner-iscsi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: transmission-pvc
spec:
  storageClassName: openebs-transmission
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 400G

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-config
data:
  settings.json: |
    {
      "bind-address-ipv4": "0.0.0.0",
      "bind-address-ipv6": "::",
      "blocklist-enabled": true,
      "blocklist-url": "http://list.iblocklist.com/?list=ydxerpxkpcfqjaybcssw&fileformat=p2p&archiveformat=gz",
      "download-dir": "/vol/mnt/downloads",
      "download-queue-enabled": true,
      "download-queue-size": 20,
      "encryption": 2,
      "incomplete-dir": "/transmission/incomplete",
      "incomplete-dir-enabled": true,
      "max-peers-global": 1000,
      "message-level": 2,
      "peer-limit-global": 1000,
      "peer-limit-per-torrent": 1000,
      "port-forwarding-enabled": false,
      "preallocation": 0,
      "queue-stalled-enabled": true,
      "queue-stalled-minutes": 5,
      "ratio-limit": 0,
      "ratio-limit-enabled": true,
      "rename-partial-files": true,
      "rpc-authentication-required": false,
      "rpc-host-whitelist": "*.internal",
      "rpc-host-whitelist-enabled": true,
      "rpc-url": "/transmission/",
      "rpc-whitelist": "127.0.0.1",
      "rpc-whitelist-enabled": false,
      "script-torrent-done-enabled": true,
      "script-torrent-done-filename": "/remove-completed.sh",
      "speed-limit-down": 800,
      "speed-limit-down-enabled": true,
      "speed-limit-up": 10,
      "speed-limit-up-enabled": true,
      "start-added-torrents": true
    }

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: transmission
spec:
  serviceName: transmission
  replicas: 1
  selector:
    matchLabels:
      k8s-app: transmission
  template:
    metadata:
      labels:
        k8s-app: transmission
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      initContainers:
      # /vol/mnt should be fuse mounted by another container
      # Verify that this is mounted before continuing
      - name: wait-mount
        image: busybox:latest
        command:
        - "/bin/mountpoint"
        args:
        - "/vol/mnt"
        volumeMounts:
        - name: torrent-vol
          mountPath: "/vol"
      - name: wireguard
        image: randomcoww/wireguard:latest
        args:
        - "up"
        - "wg0"
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - name: wireguard-config
          mountPath: /etc/wireguard/wg0.conf
          subPath: wireguard-secret
      containers:
      - name: transmission
        image: randomcoww/transmission:latest
        imagePullPolicy: Always
        env:
        - name: RESUME_DIR
          value: /transmission/resume
        - name: TORRENTS_DIR
          value: /vol/mnt/torrents
        ports:
        - containerPort: 9091
        volumeMounts:
        - name: transmission-resume
          mountPath: /transmission
        - name: transmission-config
          mountPath: /var/lib/transmission/settings.json
          subPath: settings.json
        - name: torrent-vol
          mountPath: "/vol"
      volumes:
      - name: transmission-resume
        persistentVolumeClaim:
          claimName: transmission-pvc
      - name: transmission-config
        configMap:
          name: transmission-config
      - name: wireguard-config
        secret:
          secretName: wireguard-config
      - name: torrent-vol
        persistentVolumeClaim:
          claimName: ingest-pvc

---
kind: Service
apiVersion: v1
metadata:
  name: transmission
spec:
  ports:
  - name: webui
    port: 80
    targetPort: 9091
  selector:
    k8s-app: transmission

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: transmission
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: tr.fuzzybunny.internal
    http:
      paths:
      - path: /
        backend:
          serviceName: transmission
          servicePort: webui
  tls:
  - secretName: internal-tls