apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-tgt-config
data:
  config.json: |
    {
      "storages": [
        {
          "deviceID": 1000,
          "path": "file:/vol/file",
          "online": true
        }
      ],
      "iscsiportals": [
        {
          "id": 0,
          "portal": "127.0.0.1:3260"
        }
      ],
      "iscsitargets": {
        "iqn.2016-09.com.gotgt.gostor:unifi": {
          "tpgts": {
            "1": [
              0
            ]
          },
          "luns": {
            "0": 1000
          }
        }
      }
    }

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: unifi-tgt
spec:
  selector:
    matchLabels:
      app: unifi-tgt
  template:
    metadata:
      labels:
        app: unifi-tgt
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: tgt-config
        configMap:
          name: unifi-tgt-config
      - name: unifi-tgt-vol
        emptyDir: {}
      containers:
      - name: gotgt
        image: randomcoww/gotgt:latest
        args:
        - daemon
        volumeMounts:
        - name: tgt-config
          mountPath: /root/.gotgt
        - name: unifi-tgt-vol
          mountPath: /vol
          mountPropagation: HostToContainer
        ports:
        - containerPort: 3260
      - name: s3backer
        securityContext:
          privileged: true
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-auth
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-auth
              key: secret_access_key
        image: randomcoww/s3backer:1.5.4
        args:
        - -d
        - --accessId=$(AWS_ACCESS_KEY_ID)
        - --accessKey=$(AWS_SECRET_ACCESS_KEY)
        - --baseURL=http://minio.default.svc.cluster.internal:9000/"
        - --blockSize=128k 
        - --size=2g
        - --listBlocks
        - --force
        - unifi-block
        - /vol
        volumeMounts:
        - name: unifi-tgt-vol
          mountPath: /vol
          mountPropagation: Bidirectional

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: unifi
  iscsi:
    targetPortal: 127.0.0.1:3260
    iqn: iqn.2016-09.com.gotgt.gostor:unifi
    lun: 0
    fsType: 'ext4'
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: unifi
  resources:
    requests:
      storage: 2Gi