apiVersion: v1
kind: ConfigMap
metadata:
  name: mpd-config
  namespace: common
data:
  mpd.conf: |
    user "mpd"
    bind_to_address "0.0.0.0"
    port "6600"
    music_directory "/mpd/music"
    playlist_directory "/mpd/cache/playlists"
    db_file "/mpd/cache/tag_cache"
    state_file "/mpd/cache/state"
    sticker_file "/mpd/cache/sticker.sql"
    filesystem_charset "UTF-8"
    resampler {
      plugin "soxr"
      threads "0"
      quality "very high"
    }
    audio_output {
      type "httpd"
      name "HTTP FLAC-3"
      tags "yes"
      format "48000:32:2"
      always_on "yes"
      encoder "flac"
      compression "3"
      port "8000"
      bind_to_address "0.0.0.0"
      max_clients "0"
    }

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mpd
  namespace: common
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpd
  template:
    metadata:
      labels:
        app: mpd
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      containers:
      - name: mpd
        image: randomcoww/mpd:0.21.25
        ports:
        - containerPort: 8000
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/mpd.conf
          name: mpd-config
          subPath: mpd.conf
        - mountPath: /mpd/music
          name: mpd-data
        - mountPath: /mpd/cache
          name: mpd-cache
      - name: ympd
        image: randomcoww/ympd:latest
        args:
        - "-h"
        - "127.0.0.1"
        - "-p"
        - "6600"
        - "-w"
        - "8001"
        ports:
        - containerPort: 8001
          protocol: TCP
      volumes:
      - name: mpd-config
        configMap:
          name: mpd-config
      - name: mpd-data
        persistentVolumeClaim:
          claimName: mpd-data-pvc
      - name: mpd-cache
        persistentVolumeClaim:
          claimName: mpd-cache-pvc

---
kind: Service
apiVersion: v1
metadata:
  name: mpd
  namespace: common
spec:
  ports:
  - name: stream
    port: 8000
  - name: control
    port: 8001
  selector:
    app: mpd
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mpd
  namespace: common
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: mpd.fuzzybunny.internal
    http:
      paths:
      - path: /
        backend:
          serviceName: mpd
          servicePort: control
  - host: stream.fuzzybunny.internal
    http:
      paths:
      - path: /
        backend:
          serviceName: mpd
          servicePort: stream
  tls:
  - secretName: tls-ingress