apiVersion: openebs.io/v1alpha1
kind: StoragePool
metadata:
  name: mpd
  type: hostdir
spec:
  path: "/var/pv/mpd"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-mpd
  annotations:
    openebs.io/cas-type: jiva
    cas.openebs.io/config: |
      - name: ReplicaCount
        value: "2"
      - name: StoragePool
        value: mpd
provisioner: openebs.io/provisioner-iscsi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mpd-pvc
spec:
  storageClassName: openebs-mpd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2G