apiVersion: v1
kind: Namespace
metadata:
  name: ${namespace}

---
apiVersion: v1
kind: Secret
metadata:
  name: ${name}
  namespace: ${namespace}
data:
  %{~ for k in keys(data) ~}
  ${k}: ${replace(base64encode(chomp(data[k])), "\n", "")}
  %{~ endfor ~}
type: ${type}