apiVersion: v1
kind: Secret
metadata:
  name: {{ template "headscale.fullname" . }}
  labels:
    app: {{ template "headscale.name" . }}
    chart: {{ template "headscale.chart" . }}
    release: {{ .Release.Name }}
stringData:
  ACCESS_KEY_ID: "{{ .Values.backup.accessKeyID }}"
  SECRET_ACCESS_KEY: "{{ .Values.backup.secretAccessKey }}"
  private.key: "privkey:{{ .Values.privateKey }}"
  noise_private.key: "privkey:{{ .Values.noisePrivateKey }}"