---
variant: fcos
version: 1.5.0
systemd:
  units:
    - name: chronyd.service
      enabled: true
    # enable trim on all disks
    - name: fstrim.service
      enabled: true
      dropins:
        - name: 10-all.conf
          contents: |
            [Service]
            ExecStart=
            ExecStart=/usr/sbin/fstrim --all --verbose --quiet
    - name: systemd-network-generator.service
      mask: true
    - name: systemd-resolved.service
      enabled: true
    # temperature monitoring for hardware
    - name: lm_sensors.service
      enabled: true
      dropins:
        - name: 10-exclude-vm.conf
          contents: |
            [Unit]
            ConditionVirtualization=!vm
            ConditionVirtualization=!container
    # configure nftables service as template
    - name: nftables.service
      mask: false
    - name: nftables@.service
      enabled: true
      contents: |
        [Unit]
        Wants=network-pre.target
        Before=network-pre.target
        ConditionFileNotEmpty=/etc/nftables/%i.conf

        [Service]
        Type=oneshot
        ProtectSystem=full
        ProtectHome=true
        ExecStart=/sbin/nft -f /etc/nftables/%i.conf
        ExecReload=/sbin/nft 'delete table %i; include "/etc/nftables/%i.conf";'
        ExecStop=/sbin/nft delete table %i
        RemainAfterExit=yes

        [Install]
        WantedBy=multi-user.target

storage:
  files:
    - path: /etc/hostname
      mode: 0644
      contents:
        inline:
          ${hostname}

    # No swap - disable hibernation
    - path: /etc/systemd/sleep.conf.d/10-disable-hibernate.conf
      mode: 0644
      contents:
        inline: |
          [Sleep]
          AllowHibernation=no
          AllowSuspendThenHibernate=no
          AllowHybridSleep=no

    # Disable local DNS for systemd-networkd #
    - path: /etc/systemd/resolved.conf.d/10-mdns.conf
      mode: 0644
      contents:
        inline: |
          [Resolve]
          FallbackDNS=
          DNSStubListener=false
          MulticastDNS=true
          LLMNR=false

    # Block password SSH #
    - path: /etc/ssh/sshd_config.d/10-block-password.conf
      mode: 0644
      contents:
        inline: |
          PasswordAuthentication no
    # Systemd for live image #
    - path: /etc/systemd/journald.conf.d/10-live-boot-config.conf
      mode: 0644
      contents:
        inline: |
          [Journal]
          Storage=volatile
          RuntimeMaxUse=10M
          SystemMaxUse=10M
          SystemMaxFileSize=10M
          ForwardToSyslog=false
          ForwardToConsole=false
    - path: /etc/systemd/system.conf.d/10-live-boot-config.conf
      mode: 0644
      contents:
        inline: |
          [Manager]
          DumpCore=false
    # Disable speaker #
    - path: /etc/modprobe.d/10-blacklist-pcspk.conf
      mode: 0644
      contents:
        inline: |
          blacklist pcspkr
          blacklist snd_pcsp
    # Keepalived lvs #
    - path: /etc/modules-load.d/20-keepalived.conf
      mode: 0644
      contents:
        inline: |
          ip_vs
    # DNS reply from unexpected source #
    - path: /etc/modules-load.d/20-dns-reply.conf
      mode: 0644
      contents:
        inline: |
          br_netfilter
    # mayastor #
    - path: /etc/modules-load.d/20-nvme-tcp.conf
      mode: 0644
      contents:
        inline: |
          nvme_tcp
    # Keepalived VIP #
    - path: /etc/sysctl.d/20-keepalived.conf
      mode: 0644
      contents:
        inline: |
          net.ipv4.ip_forward=1
          net.ipv4.ip_nonlocal_bind=1
    # common #
    - path: /etc/sysctl.d/10-common.conf
      mode: 0644
      contents:
        inline: |
          kernel.printk=4
          fs.inotify.max_user_watches=524288
    # needed if bridging wlan
    - path: /etc/sysctl.d/99-bridge-iptables.conf
      mode: 0644
      contents:
        inline: |
          net.bridge.bridge-nf-call-iptables=0
    # mayastor hugepages #
    - path: /etc/sysctl.d/20-hugepages.conf
      mode: 0644
      contents:
        inline: |
          vm.nr_hugepages=1024