apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    %{~ for k, v in loadbalancer_pools ~}
    - name: ${k}
      protocol: layer2
      addresses:
      - ${v.network}/${v.cidr}
    %{~ endfor ~}