apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "code.fullname" . }}
  labels:
    app: {{ template "code.name" . }}
    chart: {{ template "code.chart" . }}
    release: "{{ .Release.Name }}"
spec:
  serviceName: {{ template "code.fullname" . }}
  # Only supports 1 replica
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "code.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "code.name" . }}
        release: {{ .Release.Name }}
    spec:
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      restartPolicy: Always
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.images.code }}
        env:
        - name: CODE_PORT
          value: "{{ .Values.ports.code }}"
        volumeMounts:
        - name: code-mount
          mountPath: {{ .Values.code.mountPath }}
        ports:
        - containerPort: {{ .Values.ports.code }}
        securityContext:
          capabilities:
            add:
            - AUDIT_WRITE
          runAsUser: {{ .Values.code.uid }}
      {{- with .Values.resources }}
        resources:
{{ toYaml . | indent 10 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: code-mount
    {{- if .Values.persistence.annotations }}
      annotations:
{{ toYaml .Values.persistence.annotations | trimSuffix "\n" | indent 8 }}
    {{- end }}
    spec:
      accessModes:
      - {{ .Values.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
    {{- if .Values.persistence.storageClass }}
      storageClassName: "{{ .Values.persistence.storageClass }}"
    {{- end }}