# nodePort and clusterIP must be specified for LB services to work with
# the terraform kubernetes-alpha provider. Probably a bug?
# TODO: Remove once not needed by provider

apiVersion: v1
kind: Service
metadata:
  name: loki-lb
  namespace: monitoring
  labels:
    app: loki
spec:
  type: LoadBalancer
  loadBalancerIP: ${services.loki.vip}
  clusterIP: ${services.kubernetes_loki.vip}
  ports:
  - port: ${services.loki.ports.http_listen}
    nodePort: ${services.kubernetes_loki.ports.node}
    protocol: TCP
    name: http-metrics
    targetPort: http-metrics
  selector:
    app: loki