apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "external-dns.fullname" . }}
  labels:
    app: {{ template "external-dns.name" . }}
    chart: {{ template "external-dns.chart" . }}
    release: "{{ .Release.Name }}"
data:
  Corefile: |
    {{- range $name, $conf := .Values.extraConfig }}
    {{ $name }}{{ if $conf.parameters }} {{ $conf.parameters }}{{ end }}
    {{- end }}
    {{ range .Values.servers }}
    {{- range $idx, $zone := .zones }}{{ if $idx }} {{ else }}{{ end }}{{ default "" $zone.scheme }}{{ default "." $zone.zone }}{{ else }}.{{ end -}}
    {{- if .port }}:{{ .port }} {{ end -}}
    {
      {{- range .plugins }}
        {{ .name }}{{ if .parameters }} {{ .parameters }}{{ end }}{{ if .configBlock }} {
{{ .configBlock | indent 12 }}
        }{{ end }}
      {{- end }}
    }
    {{ end }}
  {{- range .Values.zoneFiles }}
  {{ .filename }}: {{ toYaml .contents | indent 4 }}
  {{- end }}