apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Chart.Name }}
data:
  access_key_id: {{ .Values.access_key_id }}
  secret_access_key: {{ .Values.secret_access_key }}
type: Opaque