apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Chart.Name }}
spec:
  serviceName: {{ .Chart.Name }}
  replicas: {{ .Values.replica_count }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Chart.Name }}
            topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {{ .Values.node_affinity }}
      containers:
      - name: minio
        image: {{ .Values.image }}
        imagePullPolicy: Always
        env:
        - name: INTERNAL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}
              key: access_key_id
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}
              key: secret_access_key
        - name: MINIO_ADDRESS
          value: "0.0.0.0:{{ .Values.minio_port }}"
        - name: MINIO_CONSOLE_ADDRESS
          value: "0.0.0.0:{{ .Values.minio_console_port }}"
        args:
        - server
        - {{ .Values.volume_path }}
        volumeMounts:
        - name: volume
          mountPath: {{ .Values.volume_path }}
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: {{ .Values.minio_port }}
          initialDelaySeconds: 120
          periodSeconds: 20
      volumes:
      - name: volume
        hostPath:
          path: {{ .Values.volume_path }}
          type: DirectoryOrCreate

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Chart.Name }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.minio_ip }}
  ports:
  - name: api
    port: {{ .Values.minio_port }}
    protocol: TCP
  - name: console
    port: {{ .Values.minio_console_port }}
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}