apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ${replace(base64encode(chomp(ca_pem)), "\n", "")}
    server: ${apiserver_endpoint}
  name: ${cluster_name}
contexts:
- context:
    cluster: ${cluster_name}
    user: admin
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: admin
  user:
    as-user-extra: {}
    client-certificate-data: ${replace(base64encode(chomp(cert_pem)), "\n", "")}
    client-key-data: ${replace(base64encode(chomp(private_key_pem)), "\n", "")}