apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-config
  namespace: common
data:
  settings.json: |
    {
      "bind-address-ipv4": "0.0.0.0",
      "bind-address-ipv6": "::",
      "blocklist-enabled": true,
      "blocklist-url": "http://list.iblocklist.com/?list=ydxerpxkpcfqjaybcssw&fileformat=p2p&archiveformat=gz",
      "download-dir": "/vol/data/downloads",
      "download-queue-enabled": true,
      "download-queue-size": 20,
      "encryption": 2,
      "incomplete-dir": "/vol/cache/incomplete",
      "incomplete-dir-enabled": true,
      "max-peers-global": 1000,
      "message-level": 2,
      "peer-limit-global": 1000,
      "peer-limit-per-torrent": 1000,
      "port-forwarding-enabled": false,
      "preallocation": 0,
      "queue-stalled-enabled": true,
      "queue-stalled-minutes": 5,
      "ratio-limit": 0,
      "ratio-limit-enabled": true,
      "rename-partial-files": true,
      "rpc-authentication-required": false,
      "rpc-host-whitelist": "*.internal",
      "rpc-host-whitelist-enabled": true,
      "rpc-url": "/transmission/",
      "rpc-whitelist": "127.0.0.1",
      "rpc-whitelist-enabled": false,
      "script-torrent-done-enabled": true,
      "script-torrent-done-filename": "/remove-completed.sh",
      "speed-limit-down": 1000,
      "speed-limit-down-enabled": false,
      "speed-limit-up": 10,
      "speed-limit-up-enabled": true,
      "start-added-torrents": true
    }

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: transmission
  namespace: common
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      initContainers:
      - name: wireguard
        image: randomcoww/wireguard:latest
        imagePullPolicy: Always
        args:
        - "up"
        - "wg0"
        securityContext:
          privileged: true
        volumeMounts:
        - name: wireguard-client
          mountPath: /etc/wireguard/wg0.conf
          subPath: wireguard-client
      containers:
      - name: transmission
        image: randomcoww/transmission:latest
        imagePullPolicy: Always
        env:
        - name: RESUME_DIR
          value: /vol/cache/resume
        - name: TORRENTS_DIR
          value: /vol/data/torrents
        ports:
        - containerPort: 9091
        volumeMounts:
        - name: transmission-config
          mountPath: /var/lib/transmission/settings.json
          subPath: settings.json
        - name: ingest-cache-resume
          mountPath: /vol/cache/resume
        - name: ingest-cache-incomplete
          mountPath: /vol/cache/incomplete
        - name: ingest-data-downloads
          mountPath: /vol/data/downloads
        - name: ingest-data-torrents
          mountPath: /vol/data/torrents
      volumes:
      # configs
      - name: transmission-config
        configMap:
          name: transmission-config
      - name: wireguard-client
        secret:
          secretName: wireguard-client
      # shared path for minio mount
      - name: ingest-cache-resume
        persistentVolumeClaim:
          claimName: ingest-cache-resume-pvc
      - name: ingest-cache-incomplete
        persistentVolumeClaim:
          claimName: ingest-cache-incomplete-pvc
      - name: ingest-data-downloads
        persistentVolumeClaim:
          claimName: ingest-data-downloads-pvc
      - name: ingest-data-torrents
        persistentVolumeClaim:
          claimName: ingest-data-torrents-pvc

---
kind: Service
apiVersion: v1
metadata:
  name: transmission
  namespace: common
spec:
  clusterIP: None
  ports:
  - name: web
    port: 9091
  selector:
    app: transmission

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: transmission
  namespace: common
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: tr.fuzzybunny.internal
    http:
      paths:
      - path: /
        backend:
          serviceName: transmission
          servicePort: web
  tls:
  - secretName: tls-ingress