{
 "title": "kubernetes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API server request rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Worker load (15m)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load15", "legendFormat": "{{kubernetes_node}}" }
   ]
  },
  {
   "title": "API server request latency p90",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_latencies_bucket{verb != \"WATCH\"}[5m])) by (le, verb)) / 1e3",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Worker memory usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Etcd request duration p90",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\rhistogram_quantile(0.90, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Worker disk I/O",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total[2m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}
{
 "title": "etcd",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "etcd-wrapper-controller-0",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=\"kube-etcd-wrapper\",host=\"controller-0\"}"
    }
   ]
  },
  {
   "title": "etcd-wrapper-controller-1",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container_name=\"kube-etcd-wrapper\",host=\"controller-1\"}"
    }
   ]
  },
  {
   "title": "etcd-wrapper-controller-2",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container_name=\"kube-etcd-wrapper\",host=\"controller-2\"}"
    }
   ]
  },
  {
   "title": "etcd-controller-0",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{container_name=\"etcd\",host=\"controller-0\"}"
    }
   ]
  },
  {
   "title": "etcd-controller-1",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{container_name=\"etcd\",host=\"controller-1\"}"
    }
   ]
  },
  {
   "title": "etcd-controller-2",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{container_name=\"etcd\",host=\"controller-2\"}"
    }
   ]
  }
 ]
}
{
 "title": "kube-apiserver",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "kube-apiserver-controller-0",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=\"kube-apiserver\",host=\"controller-0\"}"
    }
   ]
  },
  {
   "title": "kube-apiserver-controller-1",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{container_name=\"kube-apiserver\",host=\"controller-1\"}"
    }
   ]
  },
  {
   "title": "kube-apiserver-controller-2",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{container_name=\"kube-apiserver\",host=\"controller-2\"}"
    }
   ]
  }
 ]
}
{
 "title": "worker-network",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "kube-proxy",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=\"kube-proxy\"}"
    }
   ]
  },
  {
   "title": "flannel",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container_name=\"kube-flannel\"}"
    }
   ]
  }
 ]
}