apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "webdav.fullname" . }}
  labels:
    app: {{ template "webdav.name" . }}
    chart: {{ template "webdav.chart" . }}
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
  selector:
    matchLabels:
      app: {{ template "webdav.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "webdav.name" . }}
        release: {{ .Release.Name }}
    spec:
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      restartPolicy: Always
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.images.rclone }}
        args:
        - "serve"
        - "webdav"
        - "--addr=0.0.0.0:{{ .Values.ports.rclone }}"
        - ":s3:{{ .Values.minioBucket }}"
        - "--s3-provider=Minio"
        - "--s3-endpoint={{ .Values.minioEndPoint }}"
        - "--no-modtime"
        - "--read-only"
        ports:
        - containerPort: {{ .Values.ports.rclone }}
