apiVersion: v1
kind: Service
metadata:
  name: {{ template "desktop.fullname" . }}-sunshine
  labels:
    app: {{ template "desktop.name" . }}
    chart: {{ template "desktop.chart" . }}
    release: {{ .Release.Name }}
{{- if .Values.sunshineService.annotations }}
  annotations:
{{ toYaml .Values.sunshineService.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.sunshineService.type }}
{{- if .Values.sunshineService.clusterIP }}
  clusterIP: {{ .Values.sunshineService.clusterIP }}
{{- end }}
  ports:
{{- range $port := .Values.ports.sunshineTCP }}
  - name: sunshine-tcp-{{ $port }}
    port: {{ $port }}
    targetPort: {{ $port }}
    protocol: TCP
{{- end }}
{{- range $port := .Values.ports.sunshineUDP }}
  - name: sunshine-udp-{{ $port }}
    port: {{ $port }}
    protocol: UDP
    targetPort: {{ $port }}
{{- end }}
{{- if .Values.sunshineService.externalIPs }}
  externalIPs:
{{- range $i , $ip := .Values.sunshineService.externalIPs }}
  - {{ $ip }}
{{- end }}
{{- end }}
  selector:
    app: {{ template "desktop.name" . }}
    release: {{ .Release.Name }}