---
variant: fcos
version: 1.5.0
storage:
  files:
    # certs #
    %{~ for cert in values(pki) ~}
    - path: ${cert.path}
      mode: 0644
      contents:
        inline: "${replace(cert.content, "\n", "\\n")}"
    %{~ endfor ~}
    %{~ for cert in values(etcd_pki) ~}
    - path: ${cert.path}
      mode: 0644
      contents:
        inline: "${replace(cert.content, "\n", "\\n")}"
    %{~ endfor ~}
