---
variant: fcos
version: 1.2.0
systemd:
  units:
    - name: systemd-resolved.service
      enabled: true
    - name: chronyd.service
      enabled: true
    - name: fstrim.service
      enabled: true
      dropins:
        - name: 10-all.conf
          contents: |
            [Service]
            ExecStart=
            ExecStart=/usr/sbin/fstrim --all --verbose --quiet
storage:
  files:
    - path: /etc/hostname
      mode: 0644
      contents:
        inline:
          ${p.hostname}
    - path: /etc/systemd/resolved.conf.d/05-disable-stub.conf
      mode: 0644
      contents:
        inline: |
          [Resolve]
          FallbackDNS=
          DNSStubListener=false
          MulticastDNS=true
          LLMNR=false
    - path: /etc/ssh/sshd_config.d/10-block-password.conf
      mode: 0644
      contents:
        inline: |
          PasswordAuthentication no
    - path: /etc/systemd/journald.conf.d/05-live.conf
      mode: 0644
      contents:
        inline: |
          [Journal]
          Storage=volatile
          RuntimeMaxUse=10M
          SystemMaxUse=10M
          SystemMaxFileSize=10M
          ForwardToSyslog=false
          ForwardToConsole=false
    - path: /etc/systemd/system.conf.d/05-live.conf
      mode: 0644
      contents:
        inline: |
          [Manager]
          DumpCore=false
    - path: /etc/modprobe.d/pcsp-blacklist.conf
      mode: 0644
      contents:
        inline: |
          blacklist pcspkr
          blacklist snd_pcsp

# Remove users baked into standard CoreOS image
passwd:
  users:
    - name: core
      should_exist: false
  groups:
    - name: core
      should_exist: false