---
apiVersion: v1
kind: Namespace
metadata:
  name: ${namespace}

---
apiVersion: v1
kind: Secret
metadata:
  name: ${resource_name}-matchbox-tls
  namespace: ${namespace}
data:
  ca.crt: ${replace(base64encode(chomp(matchbox_certs.ca)), "\n", "")}
  server.crt: ${replace(base64encode(chomp(matchbox_certs.cert)), "\n", "")}
  server.key: ${replace(base64encode(chomp(matchbox_certs.key)), "\n", "")}
type: Opaque

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${resource_name}
  namespace: ${namespace}
spec:
  replicas: ${replica_count}
  selector:
    matchLabels:
      app: ${resource_name}
  template:
    metadata:
      labels:
        app: ${resource_name}
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - ${affinity_resource_name}
            topologyKey: "kubernetes.io/hostname"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - ${resource_name}
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: matchbox
        image: ${container_images.matchbox}
        args:
        - -address=0.0.0.0:${internal_pxeboot_http_port}
        - -rpc-address=0.0.0.0:${internal_pxeboot_api_port}
        - -assets-path=${matchbox_path}
        - -data-path=${matchbox_path}
        volumeMounts:
        - name: matchbox-tls
          mountPath: /etc/matchbox/ca.crt
          subPath: ca.crt
        - name: matchbox-tls
          mountPath: /etc/matchbox/server.crt
          subPath: server.crt
        - name: matchbox-tls
          mountPath: /etc/matchbox/server.key
          subPath: server.key
        - name: matchbox-data
          mountPath: ${matchbox_path}
      volumes:
      - name: syncthing-config
        configMap:
          name: ${resource_name}-syncthing-config
      - name: syncthing-tls
        secret:
          secretName: ${resource_name}-syncthing-tls
      - name: matchbox-tls
        secret:
          secretName: ${resource_name}-matchbox-tls
      - name: matchbox-data
        hostPath:
          path: ${matchbox_path}

---
kind: Service
apiVersion: v1
metadata:
  name: ${resource_name}
  namespace: ${namespace}
  labels:
    app: ${resource_name}
spec:
  type: LoadBalancer
  loadBalancerIP: ${internal_pxeboot_ip}
  ports:
  - name: rpc
    port: ${internal_pxeboot_api_port}
    targetPort: ${internal_pxeboot_api_port}
    protocol: TCP
  - name: http
    port: ${internal_pxeboot_http_port}
    targetPort: ${internal_pxeboot_http_port}
    protocol: TCP
  selector:
    app: ${resource_name}