apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replica_count }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.affinity }}
            topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Chart.Name }}
            topologyKey: kubernetes.io/hostname
      containers:
      - name: matchbox
        image: {{ .Values.image }}
        args:
        - -address=0.0.0.0:{{ .Values.internal_pxeboot_http_port }}
        - -rpc-address=0.0.0.0:{{ .Values.internal_pxeboot_api_port }}
        - -assets-path={{ .Values.data_path }}
        - -data-path={{ .Values.data_path }}
        volumeMounts:
        - name: matchbox-tls
          mountPath: /etc/matchbox/ca.crt
          subPath: ca.crt
        - name: matchbox-tls
          mountPath: /etc/matchbox/server.crt
          subPath: server.crt
        - name: matchbox-tls
          mountPath: /etc/matchbox/server.key
          subPath: server.key
        - name: matchbox-data
          mountPath: {{ .Values.data_path }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.internal_pxeboot_api_port }}
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: matchbox-tls
        secret:
          secretName: {{ .Chart.Name }}
      - name: matchbox-data
        hostPath:
          path: {{ .Values.data_path }}

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Chart.Name }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.internal_pxeboot_ip }}
  ports:
  - name: rpc
    port: {{ .Values.internal_pxeboot_api_port }}
    protocol: TCP
  - name: http
    port: {{ .Values.internal_pxeboot_http_port }}
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}