apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Chart.Name }}
data:
{{ toYaml .Values.matchbox.secret | indent 2 }}
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-{{ .Values.syncthing.podName }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Chart.Name }}
data:
{{ toYaml .Values.syncthing.secret | indent 2 }}
type: Opaque