apiVersion: v1
kind: Secret
metadata:
  name: {{ template "matchbox.fullname" . }}
  labels:
    app: {{ template "matchbox.name" . }}
    chart: {{ template "matchbox.chart" . }}
    release: "{{ .Release.Name }}"
stringData:
  ca.crt: |
{{ .Values.matchboxSecret.ca | indent 4 }}
  server.crt: |
{{ .Values.matchboxSecret.cert | indent 4 }}
  server.key: |
{{ .Values.matchboxSecret.key | indent 4 }}
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "matchbox.fullname" . }}-syncthing
  labels:
    app: {{ template "matchbox.name" . }}
    chart: {{ template "matchbox.chart" . }}
    release: "{{ .Release.Name }}"
stringData:
{{- range $i , $peer := .Values.peers }}
  cert-{{ $peer.podName }}: |
{{ $peer.syncthingCert | indent 4 }}
  key-{{ $peer.podName }}: |
{{ $peer.syncthingKey | indent 4 }}
{{- end }}
type: Opaque