apiVersion: v1
kind: Service
metadata:
  name: {{ template "matchbox.fullname" . }}
  labels:
    app: {{ template "matchbox.name" . }}
    chart: {{ template "matchbox.chart" . }}
    release: {{ .Release.Name }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end }}
  ports:
  - name: matchbox
    port: {{ .Values.service.port }}
    protocol: TCP
{{- if (and (eq .Values.service.type "NodePort") ( .Values.service.nodePort)) }}
    nodePort: {{ .Values.service.nodePort }}
{{- else }}
    targetPort: {{ .Values.ports.matchbox }}
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{- range $i , $ip := .Values.service.externalIPs }}
  - {{ $ip }}
{{- end }}
{{- end }}
  selector:
    app: {{ template "matchbox.name" . }}
    release: {{ .Release.Name }}