apiVersion: v1
kind: Service
metadata:
  name: {{ template "matchbox.fullname" . }}-sync
  labels:
    app: {{ template "matchbox.name" . }}
    chart: {{ template "matchbox.chart" . }}
    release: "{{ .Release.Name }}"
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
  - name: syncthing-peer
    port: {{ .Values.ports.syncthingPeer }}
    protocol: TCP
    targetPort: {{ .Values.syncService.port }}
  selector:
    app: {{ template "matchbox.name" . }}
    release: {{ .Release.Name }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "matchbox.fullname" . }}
  labels:
    app: {{ template "matchbox.name" . }}
    chart: {{ template "matchbox.chart" . }}
    release: "{{ .Release.Name }}"
spec:
  serviceName: {{ template "matchbox.fullname" . }}-sync
  replicas: {{ .Values.StatefulSet.replicaCount }}
  updateStrategy:
    type: {{ .Values.StatefulSet.updateStrategy }}
  minReadySeconds: {{ .Values.StatefulSet.minReadySeconds }}
  selector:
    matchLabels:
      app: {{ template "matchbox.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "matchbox.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      restartPolicy: Always
      initContainers:
      - name: {{ .Chart.Name }}-init
        image: {{ .Values.images.syncthing }}
        command:
        - "cp"
        - "/tmp/config.xml"
        - "/tmp/cert.pem"
        - "/tmp/key.pem"
        - "{{ .Values.syncthingHomePath }}/"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: syncthing-config
          mountPath: /tmp/config.xml
          subPath: config.xml
        - name: syncthing-tls
          mountPath: /tmp/cert.pem
          subPathExpr: cert-$(POD_NAME)
        - name: syncthing-tls
          mountPath: /tmp/key.pem
          subPathExpr: key-$(POD_NAME)
        - name: syncthing-home
          mountPath: {{ .Values.syncthingHomePath }}
      containers:
      - name: {{ .Chart.Name }}-sync
        image: {{ .Values.images.syncthing }}
        command:
        - syncthing
        args:
        - --home
        - {{ .Values.syncthingHomePath }}
        volumeMounts:
        - name: syncthing-home
          mountPath: {{ .Values.syncthingHomePath }}
        - name: shared-data
          mountPath: {{ .Values.sharedDataPath }}
        ports:
        - name: syncthing-peer
          containerPort: {{ .Values.ports.syncthingPeer }}
      - name: {{ .Chart.Name }}
        image: {{ .Values.images.matchbox }}
        args:
        - "-address=0.0.0.0:{{ .Values.ports.matchbox }}"
        - "-rpc-address=0.0.0.0:{{ .Values.ports.matchboxAPI }}"
        - "-assets-path={{ .Values.sharedDataPath }}"
        - "-data-path={{ .Values.sharedDataPath }}"
        volumeMounts:
        - name: matchbox-tls
          mountPath: /etc/matchbox
        - name: shared-data
          mountPath: {{ .Values.sharedDataPath }}
        ports:
        - name: matchbox-api
          containerPort: {{ .Values.ports.matchboxAPI }}
        - name: matchbox
          containerPort: {{ .Values.ports.matchbox }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.ports.matchboxAPI }}
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
      - name: {{ .Chart.Name }}-tftpd
        image: {{ .Values.images.tftpd }}
        args:
        - "--address"
        - "0.0.0.0:{{ .Values.ports.tftpd }}"
        - "--verbose"
        securityContext:
          capabilities:
            add:
            - SYS_CHROOT
            - SETUID
            - SETGID
        ports:
        - name: tftpd
          containerPort: {{ .Values.ports.tftpd }}
      volumes:
      - name: syncthing-home
        emptyDir: {}
      - name: syncthing-config
        configMap:
          name: {{ template "matchbox.fullname" . }}-syncthing
      - name: syncthing-tls
        secret:
          secretName: {{ template "matchbox.fullname" . }}-syncthing
      - name: matchbox-tls
        secret:
          secretName: {{ template "matchbox.fullname" . }}
      - name: shared-data
        emptyDir: {}