apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "headscale.fullname" . }}
  labels:
    app: {{ template "headscale.name" . }}
    chart: {{ template "headscale.chart" . }}
    release: {{ .Release.Name }}
data:
  config.yaml: |
    server_url: {{ .Values.serverURL }}
    listen_addr: 0.0.0.0:{{ .Values.ports.headscale }}
    metrics_listen_addr: 127.0.0.1:9090
    grpc_listen_addr: 127.0.0.1:50443
    grpc_allow_insecure: false
    private_key_path: {{ .Values.dataPath }}/private.key
    noise:
      private_key_path: {{ .Values.dataPath }}/noise_private.key
    ip_prefixes:
      - fd7a:115c:a1e0::/48
      - 100.64.0.0/10
    derp:
      server:
        enabled: false
      urls:
        - https://controlplane.tailscale.com/derpmap/default
      paths: []
      auto_update_enabled: true
      update_frequency: 24h
    disable_check_updates: false
    ephemeral_node_inactivity_timeout: 30m
    node_update_check_interval: 10s
    db_type: sqlite3
    db_path: {{ .Values.dataPath }}/{{ .Values.dbFile }}
    log:
      level: info
    acl_policy_path: ""
    dns_config:
      override_local_dns: false
      magic_dns: false
    unix_socket: {{ .Values.dataPath }}/headscale.sock
    unix_socket_permission: "0770"
    logtail:
      enabled: false
    randomize_client_port: false