---
variant: fcos
version: ${ignition_version}
systemd:
  units:
    # systemd-networkd work around "could not connect to dbus: permission denied"
    - name: systemd-networkd.service
      enabled: true
    - name: systemd-networkd-wait-online.service
      enabled: true
      dropins:
        - name: 10-short-delay.conf
          contents: |
            [Service]
            ExecStart=
            ExecStart=/usr/lib/systemd/systemd-networkd-wait-online --timeout=10
    - name: NetworkManager.service
      mask: true
    - name: NetworkManager-wait-online.service
      mask: true

storage:
  files:
    # systemd-networkd defaults should be unmanaged=true
    # CNI may fail if systemd-networkd tries to manage the interface
    - path: /etc/systemd/network/91-default.network
      mode: 0644
      contents:
        inline: |
          [Match]
          Name=*

          [Link]
          Unmanaged=true