apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubelet-approver
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubelet-approver
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests"]
  verbs: ["get", "list", "delete", "watch"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests/approval"]
  verbs: ["update"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["signers"]
  resourceNames: ["kubernetes.io/kubelet-serving"]
  verbs: ["approve"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubelet-approver
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubelet-approver
subjects:
- kind: ServiceAccount
  name: kubelet-approver
  namespace: kube-system

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubelet-approver
  namespace: kube-system
  labels:
    k8s-app: kubelet-approver
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kubelet-approver
  template:
    metadata:
      labels:
        k8s-app: kubelet-approver
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: kubelet-approver
      containers:
      - name: kubelet-approver
        imagePullPolicy: Always
        image: ${container_images.kapprover}
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 50Mi