---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - ${cidrsubnet(metallb_network_prefix, metallb_subnet.newbit, metallb_subnet.netnum)}