apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Chart.Name }}
data:
{{ toYaml .Values.secret_data | indent 2 }}
type: Opaque