---
variant: fcos
version: 1.4.0
storage:
  files:
    # apiserver #
    - path: ${config_path}/encryption-config.yaml
      mode: 0644
      contents:
        inline: |-
          kind: EncryptionConfig
          apiVersion: v1
          resources:
          - resources:
            - secrets
            providers:
            # not working
            # - secretbox:
            #   keys:
            #   - name: key1
            #     secret: ${encryption_config_secret}
            - identity: {}

    - path: ${static_pod_manifest_path}/kube-apiserver.yaml
      mode: 0644
      contents:
        inline: |-
          ---
          kind: Pod
          apiVersion: v1
          metadata:
            namespace: kube-system
            name: kube-apiserver
          spec:
            hostNetwork: true
            restartPolicy: Always
            containers:
            - name: kube-apiserver
              image: ${container_images.kube_apiserver}
              command:
              - kube-apiserver
              - "--advertise-address=${cidrhost(network_prefix, host_netnum)}"
              - "--allow-privileged=true"
              - "--authorization-mode=Node,RBAC"
              - "--bind-address=0.0.0.0"
              - "--client-ca-file=${kubernetes_certs.ca_cert.path}"
              - "--enable-admission-plugins=NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota"
              - "--encryption-provider-config=${config_path}/encryption-config.yaml"
              - "--etcd-cafile=${etcd_certs.ca_cert.path}"
              - "--etcd-certfile=${etcd_certs.client_cert.path}"
              - "--etcd-keyfile=${etcd_certs.client_key.path}"
              - "--etcd-servers=${join(",", etcd_servers)}"
              - "--event-ttl=1h"
              - "--kubelet-certificate-authority=${kubernetes_certs.ca_cert.path}"
              - "--kubelet-client-certificate=${kubernetes_certs.apiserver_cert.path}"
              - "--kubelet-client-key=${kubernetes_certs.apiserver_key.path}"
              - "--kubelet-preferred-address-types=InternalDNS,InternalIP"
              - "--runtime-config=api/all=true"
              - "--secure-port=${apiserver_port}"
              - "--service-account-issuer=https://kubernetes.default.svc"
              - "--service-account-key-file=${kubernetes_certs.service_account_cert.path}"
              - "--service-account-signing-key-file=${kubernetes_certs.service_account_key.path}"
              - "--service-cluster-ip-range=${kubernetes_service_network_prefix}"
              - "--tls-cert-file=${kubernetes_certs.apiserver_cert.path}"
              - "--tls-private-key-file=${kubernetes_certs.apiserver_key.path}"
              - "--v=2"
              volumeMounts:
              - name: config-apiserver
                mountPath: "${config_path}"
                readOnly: true
              - name: certs
                mountPath: "${certs_path}"
                readOnly: true
              readinessProbe:
                httpGet:
                  scheme: HTTPS
                  host: 127.0.0.1
                  port: ${apiserver_port}
                  path: "/readyz"
                initialDelaySeconds: 15
                timeoutSeconds: 15
              livenessProbe:
                httpGet:
                  scheme: HTTPS
                  host: 127.0.0.1
                  port: ${apiserver_port}
                  path: "/healthz"
                initialDelaySeconds: 15
                timeoutSeconds: 15
            volumes:
            - name: config-apiserver
              hostPath:
                path: "${config_path}"
            - name: certs
              hostPath:
                path: "${certs_path}"