---
variant: fcos
version: 1.4.0
storage:
  files:
    - path: /etc/sysctl.d/99-kubernetes-cri.conf
      mode: 0644
      contents:
        inline: |
          net.bridge.bridge-nf-call-iptables=1
          net.bridge.bridge-nf-call-ip6tables=1
          net.ipv4.ip_forward=1

    # certs #
    %{~ for cert in values(kubernetes_certs) ~}
    - path: ${cert.path}
      mode: 0644
      contents:
        inline: "${replace(cert.content, "\n", "\\n")}"
    %{~ endfor ~}