apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Chart.Name }}
data:
  hostapd.conf: {{ .Values.config | b64enc | quote }}
type: Opaque
