apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Chart.Name }}
stringData:
  hostapd.conf: |
{{- range $k, $v := .Values.config }}
    {{ $k }}={{ $v }}
{{- end }}
type: Opaque
