apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "hostapd.fullname" . }}
  labels:
    app: {{ template "hostapd.name" . }}
    chart: {{ template "hostapd.chart" . }}
    release: "{{ .Release.Name }}"
spec:
  serviceName: {{ template "hostapd.fullname" . }}
  replicas: {{ .Values.StatefulSet.replicaCount }}
  updateStrategy:
    type: {{ .Values.StatefulSet.updateStrategy }}
  minReadySeconds: {{ .Values.StatefulSet.minReadySeconds }}
  selector:
    matchLabels:
      app: {{ template "hostapd.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "hostapd.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        args:
        - /etc/hostapd/hostapd.conf
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        securityContext:
          privileged: true
        volumeMounts:
        - name: hostapd-config
          mountPath: /etc/hostapd/hostapd.conf
          subPathExpr: hostapd-$(POD_NAME)
          readOnly: true
        - name: rfkill
          mountPath: /dev/rfkill
      volumes:
      - name: hostapd-config
        secret:
          secretName: {{ template "hostapd.fullname" . }}
      - name: rfkill
        hostPath:
          path: /dev/rfkill
