apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "transmission.fullname" . }}
  labels:
    app: {{ template "transmission.name" . }}
    chart: {{ template "transmission.chart" . }}
    release: "{{ .Release.Name }}"
spec:
  serviceName: {{ template "transmission.fullname" . }}
  # Only supports 1 replica
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "transmission.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "transmission.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      restartPolicy: Always
      dnsConfig:
        options:
        - name: ndots
          value: "2"
      initContainers:
      - name: {{ .Chart.Name }}-init
        image: {{ .Values.images.transmission }}
        command:
        - "sh"
        - "-c"
        - |
          set -x \
          && cp -f /tmp/settings.json {{ .Values.transmission.homePath }}/
        volumeMounts:
        - name: config
          mountPath: /tmp/settings.json
          subPath: settings.json
        - name: transmission-home
          mountPath: {{ .Values.transmission.homePath }}
    {{- if .Values.wireguard.enabled }}
      - name: {{ .Chart.Name }}-wg
        image: {{ .Values.images.wireguard }}
        args:
        - "up"
        - "wg0"
        securityContext:
          privileged: true
        volumeMounts:
        - name: config
          mountPath: /etc/wireguard/wg0.conf
          subPath: wg0.conf
    {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.images.transmission }}
        args:
        - "--config-dir"
        - "{{ .Values.transmission.homePath }}"
        volumeMounts:
        - name: transmission-home
          mountPath: {{ .Values.transmission.homePath }}
        - name: config
          mountPath: {{ index .Values "transmission" "config" "script-torrent-done-filename" }}
          subPath: done.sh
        ports:
        - containerPort: {{ .Values.ports.transmission }}
      volumes:
      - name: config
        secret:
          secretName: {{ template "transmission.fullname" . }}
          defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: transmission-home
    {{- if .Values.persistence.annotations }}
      annotations:
{{ toYaml .Values.persistence.annotations | trimSuffix "\n" | indent 8 }}
    {{- end }}
    spec:
      accessModes:
      - {{ .Values.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
    {{- if .Values.persistence.storageClass }}
      storageClassName: "{{ .Values.persistence.storageClass }}"
    {{- end }}