apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "tailscale.name" . }}
  labels:
    app: {{ template "tailscale.name" . }}
    chart: {{ template "tailscale.chart" . }}
    release: "{{ .Release.Name }}"
subjects:
  - kind: ServiceAccount
    name: {{ template "tailscale.name" . }}
roleRef:
  kind: Role
  name: {{ template "tailscale.name" . }}
  apiGroup: rbac.authorization.k8s.io