apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "tailscale.fullname" . }}
  labels:
    app: {{ template "tailscale.name" . }}
    chart: {{ template "tailscale.chart" . }}
    release: "{{ .Release.Name }}"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: [""]
    resourceNames: [ {{ .Values.kubeSecret }} ]
    resources: ["secrets"]
    verbs: ["get", "update", "patch"]