apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "tailscale.name" . }}
  labels:
    app: {{ template "tailscale.name" . }}
    chart: {{ template "tailscale.chart" . }}
    release: "{{ .Release.Name }}"