apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-browser
  labels:
    app: music-browser
spec:
  replicas: 2
  selector:
    matchLabels:
      app: music-browser
  template:
    metadata:
      labels:
        app: music-browser
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - minio
            topologyKey: kubernetes.io/hostname
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      containers:
      - name: rclone
        imagePullPolicy: Always
        image: docker.io/rclone/rclone:latest
        args:
        - serve
        - webdav
        - --addr
        - :8080
        - :s3:music
        - --s3-provider=Minio
        - --s3-endpoint=http://$(NODE_IP):9000
        - --no-modtime
        - --read-only
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports:
        - name: http
          containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: music-browser
  labels:
    app: music-browser
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
  selector:
    app: music-browser

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: music-browser
  name: music-browser
spec:
  ingressClassName: nginx
  rules:
  - host: mb.fuzzybunny.internal
    http:
      paths:
      - backend:
          service:
            name: music-browser
            port:
              number: 8080
        path: /
        pathType: Prefix