---
apiVersion: v1
kind: Namespace
metadata:
  name: ${namespace}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${resource_name}-syncthing-config
  namespace: ${namespace}
data:
  config.xml: |-
    <configuration>
      <folder id="sync-data" label="sync-data" path="${sync_data_path}" type="sendreceive" fsWatcherEnabled="true" fsWatcherDelayS="1" rescanIntervalS="10" ignorePerms="true" autoNormalize="false">
        %{~ for member in syncthing_members ~}
        <device id="${member.device_id}"></device>
        %{~ endfor ~}
        <maxConflicts>1</maxConflicts>
        <copyOwnershipFromParent>true</copyOwnershipFromParent>
      </folder>
      %{~ for member in syncthing_members ~}
      <device id="${member.device_id}" compression="never" skipIntroductionRemovals="true">
        <address>${member.pod_name}.${resource_name}.${namespace}:${syncthing_peer_port}</address>
        <autoAcceptFolders>true</autoAcceptFolders>
      </device>
      %{~endfor~}
      <gui enabled="false"/>
      <options>
        <listenAddress>0.0.0.0:${syncthing_peer_port}</listenAddress>
        <globalAnnounceEnabled>false</globalAnnounceEnabled>
        <localAnnounceEnabled>false</localAnnounceEnabled>
        <reconnectionIntervalS>5</reconnectionIntervalS>
        <relaysEnabled>false</relaysEnabled>
        <startBrowser>false</startBrowser>
        <natEnabled>false</natEnabled>
        <urAccepted>-1</urAccepted>
        <autoUpgradeIntervalH>0</autoUpgradeIntervalH>
        <defaultFolderPath></defaultFolderPath>
        <crashReportingEnabled>false</crashReportingEnabled>
      </options>
    </configuration>

---
apiVersion: v1
kind: Secret
metadata:
  name: ${resource_name}-syncthing-tls
  namespace: ${namespace}
data:
  %{~ for member in syncthing_members ~}
  cert-${member.pod_name}: ${replace(base64encode(chomp(member.cert)), "\n", "")}
  key-${member.pod_name}: ${replace(base64encode(chomp(member.key)), "\n", "")}
  %{~ endfor ~}
type: Opaque

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${resource_name}
  namespace: ${namespace}
spec:
  serviceName: ${resource_name}
  replicas: ${replica_count}
  selector:
    matchLabels:
      app: ${resource_name}
  template:
    metadata:
      labels:
        app: ${resource_name}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - ${resource_name}
            topologyKey: "kubernetes.io/hostname"
      # Syncthing requires config.xml to be writable
      # Copy into shared volume
      initContainers:
      - name: syncthing-init
        image: ${container_images.syncthing}
        command:
        - cp
        - /tmp/config.xml
        - /tmp/cert.pem
        - /tmp/key.pem
        - ${syncthing_home_path}/
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: syncthing-config
          mountPath: /tmp/config.xml
          subPath: config.xml
        - name: syncthing-tls
          mountPath: /tmp/cert.pem
          subPathExpr: cert-$(POD_NAME)
        - name: syncthing-tls
          mountPath: /tmp/key.pem
          subPathExpr: key-$(POD_NAME)
        - name: syncthing-data
          mountPath: ${syncthing_home_path}
      containers:
      - name: syncthing
        image: ${container_images.syncthing}
        command:
        - syncthing
        args:
        - --home
        - ${syncthing_home_path}
        volumeMounts:
        - name: syncthing-data
          mountPath: ${syncthing_home_path}
        - name: sync-data
          mountPath: ${sync_data_path}
      volumes:
      - name: syncthing-config
        configMap:
          name: ${resource_name}-syncthing-config
      - name: syncthing-tls
        secret:
          secretName: ${resource_name}-syncthing-tls
      - name: syncthing-data
        emptyDir: {}
      - name: sync-data
        hostPath:
          path: ${sync_data_path}

---
apiVersion: v1
kind: Service
metadata:
  name: ${resource_name}
  namespace: ${namespace}
  labels:
    app: ${resource_name}
spec:
  clusterIP: None
  ports:
  - port: ${syncthing_peer_port}
  selector:
    app: ${resource_name}