name: Ignition update
on:
  workflow_dispatch:
  push:
    paths-ignore:
    - .github/**
    - README.md
    branches:
    - master

jobs:
  terraform:
    runs-on: arc-runner-${{ github.event.repository.name }}
    container:
      image: docker.io/hashicorp/terraform:latest
    permissions:
      contents: read
    steps:
    - name: Terraform ignition
      run: |
        git clone --depth 1 ${{ github.server_url }}/${{ github.repository }}.git src
        cd src

        terraform -chdir=ignition init
        terraform -chdir=ignition apply -auto-approve
