name: Node update reboot
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  node-update-reboot:
    runs-on: arc-runner-${{ github.event.repository.name }}
    container:
      image: docker.io/hashicorp/terraform:latest
    steps:
    - name: Init
      run: |
        set -e
        git clone --depth=1 ${{ github.server_url }}/${{ github.repository }}.git $HOME/project

        cd $HOME/project
        terraform -chdir=matchbox_client init -upgrade
        terraform -chdir=rolling_reboot init -upgrade
    - name: Matchbox
      run: |
        cd $HOME/project
        terraform -chdir=matchbox_client apply -auto-approve > /dev/null
    # - name: Reboot
    #   run: |
    #     terraform -chdir=rolling_reboot apply -auto-approve