name: Renovate bot
on:
  workflow_dispatch:
  schedule:
  - cron: "0 */2 * * *"

jobs:
  renovate:
    runs-on: arc-runner-${{ github.event.repository.name }}
    container:
      image: docker.io/renovate/renovate:latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Check for updates
      env:
        RENOVATE_PLATFORM: github
        RENOVATE_AUTODISCOVER: false
        RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RENOVATE_CONFIG_FILE: /tmp/renovate.json
      run: |
        cat > /tmp/renovate.json <<EOF
        {
          "repositories": [
            "${{ github.repository }}"
          ]
        }
        EOF

        renovate-entrypoint.sh renovate