name: Renovate bot
on:
  workflow_dispatch:
  schedule:
  - cron: "0 */2 * * *"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: arc-runner-${{ github.event.repository.name }}
    container:
      image: ghcr.io/renovatebot/renovate:latest
    permissions:
      contents: write
      pull-requests: write
      security-events: read
    steps:
    - name: Check for updates
      env:
        RENOVATE_PLATFORM: github
        RENOVATE_AUTODISCOVER: false
        RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RENOVATE_CONFIG_FILE: /tmp/renovate.json
        SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
      run: |
        set -e
        mkdir -p /usr/local/share/ca-certificates/
        echo -e "$INTERNAL_CA_CERT" > /usr/local/share/ca-certificates/ca.crt
        update-ca-certificates

        cat > $RENOVATE_CONFIG_FILE <<EOF
        {
          "repositories": [
            "${{ github.repository }}"
          ]
        }
        EOF

        renovate-entrypoint.sh renovate