name: Renovate bot
on:
  workflow_dispatch:
  schedule:
  - cron: "0 14 * * *"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: renovate-${{ github.event.repository.name }}
    container:
      image: ghcr.io/renovatebot/renovate:44.46.4@sha256:3b64619da15eec8cc7eb7e422698736d6e129bf0832e8b90fe956706cde3c133
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
    - name: Check for updates
      env:
        RENOVATE_PLATFORM: github
        RENOVATE_AUTODISCOVER: false
        # RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RENOVATE_GIT_AUTHOR: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
        RENOVATE_CONFIG_FILE: /tmp/renovate.json
      run: |
        cat > $RENOVATE_CONFIG_FILE <<EOF
        {
          "repositories": [
            "${{ github.repository }}"
          ]
        }
        EOF

        exec renovate-entrypoint.sh renovate