name: Renovate bot
on:
  workflow_dispatch:
  schedule:
  - cron: "0 16 * * *"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: renovate-${{ github.event.repository.name }}
    container:
      image: ghcr.io/renovatebot/renovate:43.77.7
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
    - name: Check for updates
      env:
        RENOVATE_PLATFORM: github
        RENOVATE_AUTODISCOVER: false
        # RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }} # pass RENOVATE_TOKEN from runner
        RENOVATE_CONFIG_FILE: /tmp/renovate-config.js
      run: |
        cat > $RENOVATE_CONFIG_FILE <<EOF
        module.exports = {
          repositories: [
            process.env.GITHUB_REPOSITORY
          ],

          secrets: {
            INTERNAL_REGISTRY: process.env.INTERNAL_REGISTRY,
            INTERNAL_REGISTRY_CERT: process.env.INTERNAL_REGISTRY_CERT,
            INTERNAL_REGISTRY_KEY: process.env.INTERNAL_REGISTRY_KEY,
            INTERNAL_REGISTRY_CA_CERT: process.env.INTERNAL_REGISTRY_CA_CERT,
          },

          onboarding: false,
          requireConfig: 'optional',
        };
        EOF

        exec renovate-entrypoint.sh renovate