name: Renovate bot
on:
  workflow_dispatch:
  schedule:
  - cron: "0 */2 * * *"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: arc-runner-${{ github.event.repository.name }}
    container:
      image: registry.default/randomcoww/renovate:v41.116.5.20250917.2347
    permissions:
      contents: write
      pull-requests: write
      security-events: read
    steps:
    - name: Check for updates
      env:
        RENOVATE_PLATFORM: github
        RENOVATE_AUTODISCOVER: false
        RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RENOVATE_CONFIG_FILE: /tmp/renovate.json
      run: |
        cat > $RENOVATE_CONFIG_FILE <<EOF
        {
          "repositories": [
            "${{ github.repository }}"
          ]
        }
        EOF

        renovate-entrypoint.sh renovate