name: Terraform update matchbox
on:
  workflow_dispatch:
  pull_request:
    branches: 
    - main
    types:
    - closed

jobs:
  terraform:
    # if: ${{ github.event.pull_request.merged }}
    runs-on: arc-runner-${{ github.event.repository.name }}
    container:
      image: docker.io/hashicorp/terraform:latest
    permissions:
      contents: read
    steps:
    - name: Update matchbox
      run: |
        apk add --no-cache \
          jq

        git clone ${{ github.server_url }}/${{ github.repository }}.git repo
        cd repo

        export AWS_ENDPOINT_URL_S3=https://$(wget -O - https://api.cloudflare.com/client/v4/accounts --header "Authorization: Bearer $CLOUDFLARE_API_TOKEN" | jq -r '.result.[0].id').r2.cloudflarestorage.com
        export AWS_ACCESS_KEY_ID=$(wget -O - https://api.cloudflare.com/client/v4/user/tokens/verify --header "Authorization: Bearer $CLOUDFLARE_API_TOKEN" | jq -r '.result.id')
        export AWS_SECRET_ACCESS_KEY=$(echo -n $CLOUDFLARE_API_TOKEN | sha256sum | awk '{print $1}')

        terraform -chdir=ignition init -upgrade
        terraform -chdir=ignition apply -f

        terraform -chdir=matchbox_client init -upgrade
        terraform -chdir=matchbox_client apply -f
