name: Write local disk
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  node-update-reboot:
    runs-on: arc-runner-${{ github.event.repository.name }}
    container:
      image: docker.io/hashicorp/terraform:latest
    steps:
    - name: Init
      run: |
        set -e
        git clone --depth=1 ${{ github.server_url }}/${{ github.repository }}.git $HOME/project

        cd $HOME/project
        terraform -chdir=write_local_disk init -upgrade

    - name: Write local disk
      run: |
        cd $HOME/project
        terraform -chdir=write_local_disk apply -auto-approve